### ISSUE TITLE
Unable to go get

### ISSUE THREAD

**Issue by kohenkatz** [emperror/handler-sentry#1]
The instructions say to use `go get handler.emperror.dev/sentry`.

Go gives me an error message:

```
go get handler.emperror.dev/sentry: unrecognized import path "handler.emperror.dev/sentry": https fetch: Get "https://handler.emperror.dev/sentry?go-get=1": x509: certificate is valid for *.netlify.com, netlify.com, not handler.emperror.dev
```

How can I get this package?

**Comment by sagikazarmark** [comment]
Chances are this handler has never been migrated to the new package path concept (`emperror.dev/handler/something`).

I'll try to migrate it to the new structure tomorrow.

**Comment by kohenkatz** [comment]
Should I open issues on the other handlers that haven't been updated as well? (Airbrake, Bugsnag, Rollbar, and Stackdriver all are like this)

**Comment by sagikazarmark** [comment]
Hm, I'm fairly sure that stackdriver is already updated, but the rest looks affected as well. I will update all of them.

**Comment by sagikazarmark** [comment]
Sorry it took so long. I've updated the remaining packages. Can you please test it? If it works, I'll tag new versions.

**Comment by kohenkatz** [comment]
`go get emperror.dev/handler/sentry` works now. Thank you!
